### ISSUE TITLE
Ask Org Admins to make Project public

### ISSUE THREAD

**Issue by AHolder1** [CAWaterBoardDataCenter/SWAMP-Bioassessment-Reporting-Module#1]

**Comment by AHolder1** [comment]
Hi @jpasner ! When you get a moment, can you help me make the [SWAMP Bioassessment Reporting Module Project](https://github.com/orgs/CAWaterBoardDataCenter/projects/4) public? Thanks so much!!!

**Comment by jpasner** [comment]
Just got to this and it looks like you've already made this repo public, awesome! Let me know if I'm missing something 😅 Otherwise I think we can close out this issue 👍

**Comment by AHolder1** [comment]
Hi-ya @jpasner ! Yup - the repo is public. I would _also_ like to make the [SWAMP Bioassessment Reporting Module **Project**](https://github.com/orgs/CAWaterBoardDataCenter/projects/4) public. In the Project settings (in the "Danger zone" section), it states that the project is "Private" and that "Only organization owners can change project visibility". Can you help me change the settings so that the **_Project_** is public?

**Comment by jpasner** [comment]
Ahhhh I see, sorry for the confusion! I've just made the **_Project_** public. Let me know if you need anything else, always happy to help!!

**Comment by AHolder1** [comment]
Perfect - thanks so much, @jpasner !
