### ISSUE TITLE
jadfveIPRGH

### ISSUE THREAD

**Issue by AHolder1** [CAWaterBoardDataCenter/SWAMP-Bioassessment-Reporting-Module#12]

**Comment by jpasner** [comment]
Hey @AHolder1! Curious if this issue is just a mistype? Happy to close it for you if so, otherwise sorry for the bother!

**Comment by AHolder1** [comment]
Hi Jake!

It was a test/example issue I created during a GitHub clinic Corey and I were leading/teaching last week. I was showing folks how issues and projects were connected. I will close the issue now. Thanks for checking - I hope your week is off to a great start!

Sincerely,

Anna Holder
Environmental Scientist & Tribal Coordinator
Office of Information Management and Analysis (OIMA)
California State Water Resources Control Board
(916) 341-5096
***@***.******@***.***>
1001 I Street, 19th Floor
Sacramento, CA 95814

Pronouns<https://assets2.hrc.org/files/assets/resources/TalkingAboutPronouns_onesheet_FINAL.pdf?_ga=2.251972811.352671447.1588286498-882885054.1588286498>: she/her

I respectfully acknowledge that I live and work on traditional, ancestral & unceded land of the Miwok<https://native-land.ca/maps/territories/miwok/>, Patwin<https://native-land.ca/maps/territories/patwin/> and Nisenan<https://native-land.ca/maps/territories/nisenan/> nations. Whose land are you on?<https://native-land.ca/>

CONFIDENTIALITY NOTICE: This Communication, with its contents, may contain confidential and/or legally privileged information. It is solely for the use of the intended recipient(s). Unauthorized interception, review, use or disclosure is prohibited and may violate applicable laws, including the Electronic Communications Privacy Act. If you are not the intended recipient, please contact the sender and destroy all copies of the communication.
